version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: dev
    command: pnpm dev
    working_dir: /repo/apps/web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/repo
      - pnpm-store:/pnpm/store

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    command: pnpm dev
    working_dir: /repo/apps/api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/repo
      - pnpm-store:/pnpm/store

  mobile:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile
      target: dev
    command: pnpm start
    working_dir: /repo/apps/mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./:/repo
      - pnpm-store:/pnpm/store

volumes:
  pnpm-store:
